# USED FOR LOADING ACTUATOR PARAMETERS

K_d0: [0, 0] # static friction torque coefficient ( tau_d0 = K_d* sign(joint_vel) )
K_d1: [0, 0] # dynamical friction torque coefficient ( tau_d1 = K_d* joint_vel )

rotor_axial_MoI: [6.6e-5, 6.6e-5] # approximate axial moment of inertia of the rotor ([Kg m^2]); real value 6.5717708e-5
rotor_mass: [0.27, 0.27] # mass of the rotor ([Kg])

red_ratio: [1, 1] # gear reduction ratio of the actuator (always <=1)

efficiency: [1, 1] # harmonic drive efficiency

K_t: [0.045, 0.045] # from datasheets: 0.045; torque constant ([Nm/A])
K_bmf: [3.70037, 3.70037] # ([V/Krpm])

R: [0.039, 0.039]  # resistance (per phase?) ([Ohm])

tau_max: [0.5, 0.5] # maximum continuous torque before reduction ([Nm])
tau_peak: [2.0, 2.0] # maximum continuous torque before reduction ([Nm])

I_max: [65.0, 65.0] # current @ tau_max
I_peak: [65.0, 65.0] # current @ tau_peak ([A])

max_V: [32.0, 32.0] # [V]

mass: [0.42, 0.42] # [Kg]

omega_max: [904.0, 904.0] # maximum no-load velocity